<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function panels_selective_ipe_ctools_plugin_api($module, $api) {
  if ($module == 'panels' && $api == 'pipelines') {
    return array(
      'version' => 1,
      'path' => drupal_get_path('module', 'panels_selective_ipe') . '/includes',
    );
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function panels_selective_ipe_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels' && $plugin_type == 'display_renderers') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Check the extended layout plugins if region is disabled.
 */
function _panels_selective_ipe_region_is_ipe_enabled($region_id, $plugin) {
  if (!isset($plugin['layout']['ipe_disabled'])) {
    return TRUE;
  }
  if (in_array($region_id, $plugin['layout']['ipe_disabled'])) {
    return FALSE;
  }
  return TRUE;
}
